sudo: required
language: generic

services:
  - docker

before_install: 
  - docker build -t elsmob/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true elsmob/docker-react npm run test -- --coverage

before_deploy: "echo 'ready?'"

deploy:
  provider: s3
  access_key_id: 
    secure: "HypAeHp7Sxjl0Nca1/RPiDi24mLWvxTHIRjBh0A6lQXfQEJ3+16DuQv7kuU0v7zsICoe4jebV4Kfz2vALC9KqA9Upy+bS8zr2TCSy22K0YKrLHFqwCq87+O1tOWKq0hIrm842O1QteNq8pEcuI4hNPzEVZ9vIKfWlA1t7hqcqrqZi9Rzqq9TA0hdp5A1RXSmgb/2BKPJ4TKafVi/rVXzGswbvfvprwDA9FKper8o/vXQ1nMxv4ohEtAE3g2ynszy68uk80xLvZJCpJIHWl0UrwnH3oEMz2rJhZyzcvHOeJQZOW8LB+e91o/SYzcobgY9pOK8cSdvSxMriqdlPI2EtZ2OWdxKuCZ+N72IlVUdTpfXXdkl1lcgxCu+y33bxRVS3R5BXAyQYkowjGx3FToZjkcY+Vl2ZAtMQisna0Ex3X5mSGAbiow5j7jtmYsONVjz/+jYbX7a+4TESPPTJ6qr5bOZ7WiHQSAOqFQ3nROReTCO15UtsHSt/2JRRq/PMkjg1cyxszrUsXQQmVXBEEzouydU22X2K43foS4mLr+VjgzYQabXR6s0gen8k6Z9upJ2uCKsyNIW6wkI7cUqC3NBsR10MKFP21g7fNkBKNMV13aylLZ0DTO19Fw4Bku3ZOKOrvz6sDeDvLnrEhXBchYSflGde9ThQWi2NAW2nDyGgcs="
  secret_access_key: 
    secure: "DHPLmswx5CrbQzYRNWBxAW4uyUBSoA1Jvgf07FR7C4DKUsmWNSZShCQPRtNMXGQO/kqmQF1HfAY2FTBdCIPzeQkpn5Cd1bmqMtrmbw+/SmybYiZhHe24QE7GQde6mpoVNPF7Xz4t6xAYrXj5Uhni2Lhh2l+aYp6eTKHDFFoIPHDs6DucGF05vd5etETPOMqV6th3JSQxSK3KFVqjr1w6Iys8YZv00nKdoKroJMM79ralJRPxwb1B4CodX/C/E8JmVItHDe0rc+uy8VBver5T1mKqeuAO8xYzLAcFUdQJ6WObFBU+Sdwg7W2B5fgUA9Wd8Qan3fdyuOHL9b3yXE1DWmAZfV7Z1TpGTgwSBN9X1Lzrxb+kgd1Bi/06S80RwuhVOWHQh76VYIXiTPm4HD5EMZX08ekhtRURRyX32WTo7OD+J/hRbfhsov1jDjjyearPGkbJ8Va3TaU4m12NU9FK+8JMB7nlxUg5loZ6192QICCStO7y35R+2zOCAOUTLmB2B5MeEcFGtec2cDjS1qAEwBQmn65K1XofUflAUjpIMPAombIeyteaRpMBQtHhPpPsmB8g4BgfSIntnTTEfz5AbBdbUU2b5isO21N610jWFneV1XToluNWperNfgmdPnQWmcXeYftrjrlwQ5A1Qp/4sxVrQTBzIfo7XwzvuNpEzPc=" 
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket: "elasticbeanstalk-us-east-1-256221158227"
  bucket_path: "docker-react"
  on:
    branch: master

  