sudo: required
language: generic

services:
  - docker

before_install: 
  - docker build -t elsmob/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true elsmob/docker-react npm run test -- --coverage