sudo: required
language: generic

services:
  - docker

before_install: 
  - docker build -t elsmob/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true elsmob/docker-react npm run test -- --coverage

before_deploy: "echo 'ready?'"

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-256221158227"
  bucket_path: "docker-react"
  on:
    branch: master

  